name: Release

on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    create-assets:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create release archive
              run: |
                  cd custom_components
                  zip -r ../inworld_tts.zip inworld_tts/

            - name: Upload release assets
              run: |
                  gh release upload "${{ github.event.release.tag_name }}" inworld_tts.zip --clobber
              env:
                  GH_TOKEN: ${{ github.token }}
